apiVersion: apps/v1
kind: Service
metadata:
  name: minio-service-dr
  namespace: stage
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
  type: ClusterIP

